
FROM php:8.1-apache

RUN apt-get update && apt-get install -y libzip-dev unzip mariadb-client && docker-php-ext-install zip mysqli pdo_mysql

RUN apt-get update &&apt-get install -y cron
CMD ["service","cron","start"]

RUN a2enmod rewrite

COPY ./moodle /var/www/html

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80

