#version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: moodle_db
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: moodle_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moodle_net

  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodle_web
    environment:
      MOODLE_DB_HOST: db
      MOODLE_DB_USER: moodle_user
      MOODLE_DB_PASSWORD: moodle_password
      MOODLE_DB_NAME: moodle
    ports:
      - "8080:80"
    volumes:
      - moodle_data:/var/www/html
    networks:
      - moodle_net

volumes:
  db_data:
  moodle_data:

networks:
  moodle_net:
    driver: bridge
    