
services:
    web:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: lamp_web
      ports:
        - "8080:80"                  # Exponemos el puerto 80 del contenedor al 8080 del host
      volumes:
        - ./html:/var/www/html       # Montamos los archivos de la página web
      depends_on:
        - db                         # Aseguramos que el contenedor de MySQL se inicie antes
      networks:
        - lamp_net
  
    db:
      image: mariadb:latest          # Usamos MariaDB como base de datos
      container_name: lamp_db
      environment:
        MYSQL_DATABASE: proyectos       # Nombre de la base de datos
        MYSQL_USER: root         # Usuario
        MYSQL_PASSWORD: root_password # Contraseña
        MYSQL_ROOT_PASSWORD: root_password
      volumes:
        - db_data:/var/lib/mysql     # Almacenamos los datos de la base de datos
        - ./sql:/docker-entrypoint-initdb.d # Opcional: scripts SQL iniciales
      ports:
        - "3306:3306"                # Exponemos el puerto de MySQL
      networks:
        - lamp_net

volumes:
  db_data:
  
networks:
  lamp_net:
    driver: bridge